version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cw-planning-poker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-msdesn59dhit"
s3_prefix = "cw-planning-poker"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"cw_planning_poker_connections\""
image_repositories = []
